var express=require('Express');
var app=express();
var register=require('./rejister.js');
var login=require('./login.js');
var welcome=require('./welcome.js');
var createPost=require('./createPost.js');
var forum=require('./forum.js');
var wall=require('./wall.js');
var changedp=require('./changedp.js');
var verify=require('./sentiment.js');
var logout=require('./destroy.js');
var postmentor=require('./mentor.js');
var getmentor=require('./getMentor.js');
var profiledetail=require('./profiledetail.js');
app.use(welcome);
app.use(register);
app.use(login);
app.use(createPost);
app.use(forum);
app.use(wall);
app.use(changedp);
app.use(verify);
app.use(logout);
app.use(postmentor);
app.use(getmentor);
app.use(profiledetail);
app.listen(3000);
